### ISSUE TITLE
REQ-1 변경 건의

### ISSUE THREAD

**Issue by makerdark98** [cau-sw-engineering-2021/online-pizza-ordering-system#3]
REQ-1
```
The system shall show menus of pizzas. When a pizza is clicked, the system shall allow choosing toppings and size options etc.
```
에서 피자를 단일로만 시킬수 있다고 해석이 되는데,
```
The system shall show menus of pizzas.
```
시스템은 피자 목록을 보여줘야 한다.
```
The system shall allow choosing toppings and size option etc when an item of pizza menu is clicked.
```
피자를 클릭했을 때 옵션을 고를수 있어야한다.
```
The system shall able to put items in the cart with all options selected.
```
옵션을 다 고른 피자는 카트에 넣을 수 있어야한다.

이렇게 3가지로 분리하는 것은 어떤가 싶습니다.

**Comment by alertjjm** [comment]
강의자료의 'The system shall keep the door locked at all times, unless commanded otherwise by authorized user. When the lock is
disarmed, a countdown shall be initiated at the end of which the lock shall be automatically armed (if still disarmed).'을 보고 이정도는 한번에 묶어도 되겠다 생각했는데, 저거는 세개로 쪼개는게 맞는것 같습니다 수정하겠습니다!
